# Pre-Lab


In [67]:
import random
from random import *

NORD=0
SOUTH=2
WEST=1
EST=3

class Game:
    ACTION_UP = 0
    ACTION_LEFT = 1
    ACTION_DOWN = 2
    ACTION_RIGHT = 3

    ACTIONS = [ACTION_DOWN, ACTION_LEFT, ACTION_RIGHT, ACTION_UP]

    ACTION_NAMES = ["UP", "LEFT", "DOWN", "RIGHT"]

    MOVEMENTS = {
        ACTION_UP: (1, 0),
        ACTION_RIGHT: (0, 1),
        ACTION_LEFT: (0, -1),
        ACTION_DOWN: (-1, 0)
    }

    num_actions = len(ACTIONS)

    def __init__(self, n, m, alea=False):
        self.n = n
        self.m = m
        self.alea = alea
        self.generate_game()



    def _position_to_id(self, x, y):
        return x + y * self.n

    def _id_to_position(self, id):
        return (id % self.n, id // self.n)

    def generate_game(self):


        self.position = (0,0)
        self.end = (2,3)
        self.hole = (1,3)
        self.block = (1,1)
        self.counter = 0
        
        if not self.alea:
            self.start = (0,0)
        return self._get_state()
    
    def reset(self):
        if not self.alea:
            self.position = self.start
            self.counter = 0
            return self._get_state()
        else:
            return self.generate_game()

    def _get_grille(self, x, y):
        grille = [
            [0] * self.n for i in range(self.m)
        ]
        grille[x][y] = 1
        return grille

    def _get_state(self):
        if self.alea:
            return [self._get_grille(x, y) for (x, y) in
                    [self.position, self.end, self.hole, self.block]]
        return self._position_to_id(*self.position)

    
    def move(self, action):
        """
        takes an action parameter
        :param action : the id of an action
        :return ((state_id, end, hole, block), reward, is_final, actions)
        """
        
        self.counter += 1

        if action not in self.ACTIONS:
            raise Exception("Invalid action")

        # random actions sometimes (2 times over 10 default)
        # choice = random.random()
        # if choice < self.wrong_action_p:
        #     action = (action + 1) % 4
        # elif choice < 2 * self.wrong_action_p:
        #     action = (action - 1) % 4

        nombreRandom = randint(1,10)
        orientationRandom=-1
        if(nombreRandom==1):
            orientationRandom=1
        if(nombreRandom==2):
            orientationRandom=2
        if(nombreRandom>2):
            orientationRandom=0
            
        if(action==NORD):
            if(orientationRandom==0):
                action=NORD
            if(orientationRandom==1):
                action=WEST
            if(orientationRandom==2):
                action=EST
        elif(action==EST):
            if(orientationRandom==0):
                action=EST
            if(orientationRandom==1):
                action=NORD
            if(orientationRandom==2):
                action=SOUTH
        elif(action==WEST):
            if(orientationRandom==0):
                action=WEST
            if(orientationRandom==1):
                action=NORD
            if(orientationRandom==2):
                action=SOUTH
        elif(action==SOUTH):
            if(orientationRandom==0):
                action=SOUTH
            if(orientationRandom==1):
                action=EST
            if(orientationRandom==2):
                action=WEST
                
        d_x, d_y = self.MOVEMENTS[action]
        x, y = self.position
        new_x, new_y = x + d_x, y + d_y

        if self.block == (new_x, new_y):
            return self._get_state(), -0.02, False, self.ACTIONS
        elif self.hole == (new_x, new_y):
            self.position = new_x, new_y
            return self._get_state(), -1, True, None
        elif self.end == (new_x, new_y):
            self.position = new_x, new_y
            return self._get_state(), 1, True, self.ACTIONS
        elif new_x >= self.n or new_y >= self.m or new_x < 0 or new_y < 0:
            return self._get_state(), -0.02, False, self.ACTIONS
        # elif self.counter > 190:
        #     self.position = new_x, new_y
        #     return self._get_state(), -10, True, self.ACTIONS
        else:
            self.position = new_x, new_y
            return self._get_state(), -0.02, False, self.ACTIONS

    def print(self):
        str = ""
        for i in range(self.n - 1, -1, -1):
            for j in range(self.m):
                if (i, j) == self.position:
                    str += "| x | "
                elif (i, j) == self.block:
                    str += "| b | "
                elif (i, j) == self.hole:
                    str += "| h | "
                elif (i, j) == self.end:
                    str += "| e | "
                else:
                    str += "| - | "
            str += "\n"
        print(str)

In [74]:
game = Game(3,4)
game.print()

V = np.zeros([game.n,game.m])


| - | | - | | - | | e | 
| - | | b | | - | | h | 
| x | | - | | - | | - | 



In [71]:
import numpy as np

states_n = 11
actions_n = 4
Q = np.zeros([states_n, actions_n])

# Set learning parameters
# lr = .85
y = .99
num_episodes = 1000
cumul_reward_list = []
actions_list = []
states_list = []
game = Game(3, 4) 

for i in range(num_episodes):
    for LIGNE in game.n:
        for COL in game.m:
            max_actions = list()
            for action in actions_n:
                s=0
                for  




# for i in range(num_episodes):
#     actions = []
#     s = game.reset()
#     states = [s]
#     cumul_reward = 0
#     d = False
#     while True:
#         # on choisit une action aléatoire avec une certaine probabilité, qui décroit
#         # TODO : simplifier ça (pas clair)
#         Q2 = Q[s,:] + np.random.randn(1, actions_n)*(1. / (i +1))
#         a = np.argmax(Q2)
#         s1, reward, d, _ = game.move(a)
#         Q[s, a] = Q[s, a] + lr*(reward + y * np.max(Q[s1,:]) - Q[s, a]) # Fonction de mise à jour de la Q-table
#         cumul_reward += reward
#         s = s1
        
#         actions.append(a)
#         states.append(s)
#         if d == True:
#             break
#         # game.print()
#     states_list.append(states)
#     actions_list.append(actions)
#     cumul_reward_list.append(cumul_reward)

# print("Score over time: " +  str(sum(cumul_reward_list[-100:])/100.0))

# game.reset()
# game.print()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import matplotlib.pyplot as plt
plt.plot(rList[:100])
plt.ylabel('Cumulative reward')
plt.xlabel('Étape')
plt.show()

NameError: name 'rList' is not defined